"use client";

import { useState, useCallback, useEffect } from "react";

/**
 * Displays illustrated story panels generated by Imagen 3.
 * Fetches panels when organism + script are available, shows a
 * horizontal scrollable gallery with captions.
 */
export default function StoryPanels({ organism, script }) {
  const [panels, setPanels] = useState([]);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState(null);
  const [activePanel, setActivePanel] = useState(0);

  const fetchPanels = useCallback(async () => {
    if (!organism || !script) return;

    setLoading(true);
    setError(null);
    setPanels([]);

    try {
      const response = await fetch("/api/story-panels", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ organism, script }),
      });

      const data = await response.json();

      if (!response.ok) {
        throw new Error(data.error || "Failed to generate panels");
      }

      setPanels(data.panels || []);
    } catch (err) {
      console.error("Story panels error:", err);
      setError("Could not generate illustrations");
    } finally {
      setLoading(false);
    }
  }, [organism, script]);

  // Auto-fetch when script becomes available
  useEffect(() => {
    if (script && organism) {
      fetchPanels();
    }
  }, [script, organism, fetchPanels]);

  if (!script) return null;

  return (
    <div className="space-y-3">
      <div className="flex items-center justify-between">
        <h4 className="text-xs font-medium text-stone-500 uppercase tracking-wider">
          Illustrated Story
        </h4>
        {panels.length > 0 && (
          <span className="text-xs text-stone-600">
            {activePanel + 1} / {panels.length}
          </span>
        )}
      </div>

      {/* Loading state */}
      {loading && (
        <div className="flex items-center justify-center gap-3 p-8 bg-stone-800/50 rounded-xl border border-stone-700/30">
          <div className="flex flex-col items-center gap-3">
            <div className="w-8 h-8 border-2 border-violet-400 border-t-transparent rounded-full animate-spin" />
            <span className="text-xs text-stone-500">
              Painting illustrations...
            </span>
          </div>
        </div>
      )}

      {/* Error state */}
      {error && !loading && (
        <div className="p-3 bg-stone-800/30 rounded-xl border border-stone-700/20">
          <p className="text-xs text-stone-500">{error}</p>
          <button
            onClick={fetchPanels}
            className="mt-1 text-xs text-emerald-400 underline underline-offset-2"
          >
            Try again
          </button>
        </div>
      )}

      {/* Panel gallery */}
      {panels.length > 0 && !loading && (
        <div className="space-y-2">
          {/* Main panel display */}
          <div className="relative overflow-hidden rounded-xl border border-stone-700/30 bg-stone-900">
            <img
              src={panels[activePanel]?.imageData}
              alt={panels[activePanel]?.caption || "Story illustration"}
              className="w-full aspect-[4/3] object-cover"
            />
            {/* Caption overlay */}
            <div className="absolute bottom-0 inset-x-0 bg-gradient-to-t from-stone-950/90 to-transparent p-3 pt-8">
              <p className="text-xs text-stone-300 leading-relaxed line-clamp-2">
                {panels[activePanel]?.caption}
              </p>
            </div>
          </div>

          {/* Panel thumbnails */}
          {panels.length > 1 && (
            <div className="flex gap-2">
              {panels.map((panel, index) => (
                <button
                  key={index}
                  onClick={() => setActivePanel(index)}
                  className={`flex-1 overflow-hidden rounded-lg border-2 transition-all ${
                    activePanel === index
                      ? "border-emerald-500/50 opacity-100"
                      : "border-stone-700/30 opacity-60 hover:opacity-80"
                  }`}
                >
                  <img
                    src={panel.imageData}
                    alt={`Panel ${index + 1}`}
                    className="w-full aspect-[4/3] object-cover"
                  />
                </button>
              ))}
            </div>
          )}
        </div>
      )}
    </div>
  );
}
